# Server configuration
server:
  port: 5000
  servlet:
    context-path: /api


# Spring Boot configuration
spring:
  application:
    name: Open-Api
  profiles:
    active: development
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.bsm.pub:5432/core
    username: bsm_core
    password: bsm_core
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  flyway:
    enabled: false
  jackson:
    default-property-inclusion: non_null

#My batis
mybatis:
  mapper-locations: classpath*:mappers/*.xml

# Logger configuration
logging:
  level:
    org.springframework: INFO
    com.bsm: DEBUG
  path: /logs
